from django.conf.urls import patterns, url
from tracking import views
import django.contrib.auth.views
urlpatterns = patterns('',
                       # ex: /polls/
                     
                      url(r'^logout$', django.contrib.auth.views.logout_then_login ,{'login_url':'/tracking/home'},name='logout'),
                      url(r'^register$',views.register, name='register'),
                      url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/tracking/user/password/reset/done/'}, name="password_reset"),
                      url(r'^user/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
                      url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$','django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/tracking/user/password/done/'}, name="password"),
                      url(r'^user/password/done/$','django.contrib.auth.views.password_reset_complete'),
                      url(r'^home$',views.home, name="home"),
                      url(r'^newlogin$',views.newlogin, name="newlogin"),
                      url(r'^login2$', views.login2, name="login2"),
                      url(r'^submission/$',views.manuscriptSubmission, name="submission"),
                      url(r'^createjournal/$', views.createJournal, name="createjournal"),
                      url(r'^uploadfile/(?P<mid>\d+)/$',views.dropZone, name='uploadfile'),
                      url(r'^mymanuscriptlist/$',views.manuscriptlisting, name="mymanuscriptlist"),
                      url(r'^manuscriptdetails/(?P<mid>\d+)/$',views.manuscriptview, name="manuscriptdetails"),
                      url(r'^manuscriptupdate/(?P<mid>\d+)/$',views.manuscriptupdate,name="manuscriptupdate"),
                      url(r'^reviewpage/(?P<mid>\d+)/$',views.commentpage, name="commentpage"),
                      url(r'^ajaxcreatereview/(?P<mid>\d+)/$',views.ajaxcreatereview, name="ajaxcreatereview"),
                      url(r'^updatereview/(?P<rid>\d+)/$',views.updatereview, name="updatereview"),
                      url(r'^ajaxaddcomment/(?P<rid>\d+)/(?P<mid>\d+)/$',views.ajaxaddcomment, name="ajaxaddcomment"),
                      url(r'^reviewupload/(?P<mid>\d+)/$',views.dropReviewZone, name="reviewupload"),
                      url(r'^addmanuscriptcomment/(?P<mid>\d+)/$',views.ajaxaddmanuscriptcomment, name="ajaxaddmanuscriptcomment"),
                      url(r'^accesscode/$',views.enteraccesscode, name="accesscode"),
                      url(r'^reviewdetails/$',views.reviewtab, name="reviewtab"),
                      url(r'^updateprofile/(?P<pid>\d+)/$',views.updateprofile, name="updateprofile"),
                      url(r'^changepassword/$',views.resetpassword, name="updatepassword"),
                      url(r'^adminsubmission/$',views.admincreatemanuscript, name="adminsubmission"),
                      url(r'^adminuploadfile/(?P<mid>\d+)/$',views.admindropZone, name="adminuploadfile"),
                      url(r'^adminmanuscriptlist/$',views.adminmanuscriptlist, name="adminmanuscriptlist"),
                      url(r'^adminmanuscriptdetails/(?P<mid>\d+)/$',views.adminmanuscriptdetails, name="adminmanuscriptdetails"),
                      url(r'^adminmanuscriptupdate/(?P<mid>\d+)/$',views.adminmanuscriptupdate, name="adminmanuscriptupdate"),
                      url(r'^reviewerbuffer/(?P<mid>\d+)/$',views.reviewerbuffer, name="reviewerbuffer"),
                      url(r'^searchaccesscodes/$',views.manuscriptvisible, name = "searchaccesscode"),
                      url(r'^reviewersdetails/(?P<mid>\d+)/$', views.reviewersdetails, name="reviewersdetails" ),
                      url(r'^reviewvote/(?P<rid>\d+)/$', views.voting, name= "reviewvote"),
                      url(r'^manuscriptvote/(?P<mid>\d+)/$', views.manuscriptVoting, name= "manuscriptvote"),
                      url(r'^resetinboxcount$',views.resetInboxCount,name = "resetinboxcount"),
                      url(r'^fetchnotification',views.fetchNotification, name = "fetchnotification"),
                      url(r'^activities/(?P<uid>\d+)/$',views.activitiesDetails, name = "activitiesdetails"),
                      
                      ) 
