from django.conf.urls import patterns, url
from journal import views
urlpatterns = patterns('',
                       url(r'^createprofileadmin/$',views.createprofiledetailsadmin, name="createprofileadmin"),
                       url(r'^createprofile/$',views.createprofiledetails, name="createprofile"),
                       url(r'^viewprofile/(?P<pid>\d+)/$',views.viewprofiledetails,name="viewprofile"),
                       url(r'^updateprofile/(?P<pid>\d+)/$',views.updateprofiledetails, name="updateprofile"),
                       url(r'^updateprofileadmin/(?P<pid>\d+)/$',views.updateprofiledetailsadmin, name="updateprofileadmin"),
                       url(r'^createpubarticle/$',views.createPublishedManuscriptAdmin, name="createpubmanuscriptadmin"),
                       url(r'^updatepubarticle/(?P<pid>\d+)/$',views.updatePublishedManuscriptAdmin, name="updatemanuscriptadmin"),
                       url(r'^article/(?P<aid>\d+)/$', views.articlefulldetails, name="fullarticle"),
                       url(r'^all/$',views.journalhome, name="journalhome"),
                       url(r'^instructionsubmission/$',views.submissioninstructions, name="submissioninstructions"),
                       url(r'^reviewerguide/$',views.reviewerguidelines , name = "reviewerguide"),
                       url(r'^contact/$',views.contact, name="contact"),
                       url(r'^subjectslist/$',views.journallist, name="journallist"),
                       url(r'^(?P<linkid>[a-zA-Z]+)/$',views.journalpagehome, name="journalpagehome"),
                       url(r'^(?P<linkid>[a-zA-Z]+)/article/$',views.journalarticle, name="journalarticle"),
                       url(r'^(?P<linkid>[a-zA-Z]+)/ebmembers/$',views.journalebmembers, name="journalebmembers"),
                       url(r'^(?P<linkid>[a-zA-Z]+)/instructions/$',views.journalinstructionsauthor, name="journalinstructions"),
                       url(r'^(?P<linkid>[a-zA-Z]+)/about/$',views.journalabout, name="journalabout"),
                       
                       
                       
#                        url(r'^immunity/$',views.journalpagehome, {'jid':1},name="immunityhome"),
#                        url(r'^immunityarticles/$',views.journalarticle,{'jid':1},name="immunityarticles"),
#                        url(r'^immunityeblist/$',views.journalebmembers,{'jid':1}, name = "immunityeblist"),
#                        url(r'^immunityinstructions/$',views.journalinstructionsauthor,{'jid':1},name="immunityinstructions"),
#                        url(r'^cancer/$',views.journalpagehome, {'jid':3},name="cancerhome"),
#                        url(r'^cancerarticles/$',views.journalarticle,{'jid':3},name="cancerarticles"),
#                        url(r'^cancereblist/$',views.journalebmembers,{'jid':3}, name = "cancereblist"),
#                        url(r'^cancerinstructions/$',views.journalinstructionsauthor,{'jid':3},name="cancerinstructions"),
#                        url(r'^cancerabout/$',views.journalabout,{'jid':3}, name = "cancerabout"),
#                        url(r'^cell/$',views.journalpagehome, {'jid':2},name="cellhome"),
#                        url(r'^cellarticles/$',views.journalarticle,{'jid':2},name="cellarticles"),
#                        url(r'^celleblist/$',views.journalebmembers,{'jid':2}, name = "celleblist"),
#                        url(r'^cellinstructions/$',views.journalinstructionsauthor,{'jid':2},name="cellinstructions"),
#                        url(r'^plantphysiology/$',views.journalpagehome, {'jid':5},name="plantphysiologyhome"),
#                        url(r'^plantphysiologyarticles/$',views.journalarticle,{'jid':5},name="plantphysiologyarticles"),
#                        url(r'^plantphysiologyeblist/$',views.journalebmembers,{'jid':5}, name = "plantphysiologyeblist"),
#                        url(r'^plantphysiologyinstructions/$',views.journalinstructionsauthor,{'jid':5},name="plantphysiologyinstructions"),
#                        url(r'^computationalbiology/$',views.journalpagehome, {'jid':6},name="computationalbiologyhome"),
#                        url(r'^computationalbiologyarticles/$',views.journalarticle,{'jid':6},name="computationalbiologyarticles"),
#                        url(r'^computationalbiologyeblist/$',views.journalebmembers,{'jid':6}, name = "computationalbiologyeblist"),
#                        url(r'^computationalbiologyinstructions/$',views.journalinstructionsauthor,{'jid':6},name="computationalbiologyinstructions"),
#                        url(r'^genes/$',views.journalpagehome, {'jid':4},name="geneshome"),
#                        url(r'^genesarticles/$',views.journalarticle,{'jid':4},name="genesarticles"),
#                        url(r'^geneseblist/$',views.journalebmembers,{'jid':4}, name = "geneseblist"),
#                        url(r'^genesinstructions/$',views.journalinstructionsauthor,{'jid':4},name="genesinstructions"),
#                        url(r'^journalistjson/$',views.journalistjson, name="journalistjson"),
                       
                       )